name: Auto Resolve Merge Conflicts

on:
  workflow_dispatch:  # 手动触发
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: number

jobs:
  resolve-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "MergeBot"
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename -s .git ${{ github.repository }})
          git fetch origin pull/${{ inputs.pr_number }}/head:pr-branch
          git checkout pr-branch
          git fetch origin $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          
          if ! git merge --no-commit --no-ff origin/$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'); then
            echo "has_conflicts=true" >> $GITHUB_ENV
          else
            echo "has_conflicts=false" >> $GITHUB_ENV
          fi

      - name: Extract Conflict Files
        if: env.has_conflicts == 'true'
        run: |
          cd $(basename -s .git ${{ github.repository }})
          git diff --name-only --diff-filter=U > conflict_files.txt
          cat conflict_files.txt

      - name: Resolve Conflicts with AI
        if: env.has_conflicts == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        run: python3 .github/scripts/resolve_conflicts.py

      - name: Commit and Push if Changes Exist
        if: env.has_conflicts == 'true'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "bot@github.com"
            git config --global user.name "MergeBot"
            git add .
            git commit -m "Auto-resolved merge conflicts using AI"
            git push origin HEAD:pr-branch
          fi
